apiVersion: v1
data:
  re.yaml: YXBpVmVyc2lvbjogdjEKZGF0YToKICByZS55YW1sOiAiIgpraW5kOiBTZWNyZXQKbWV0YWRhdGE6CiAgY3JlYXRpb25UaW1lc3RhbXA6IG51bGwKICBuYW1lOiBhZGRpdGlvbmFsLXNjcmFwZS1jb25maWdzCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
