apiVersion: v1
kind: Pod
metadata:
  name: redis-test
spec:
  containers:
  - name: redis-test
    command: [ "/bin/sh", "-c", "sleep infinity" ]
    image: golang
    volumeMounts:
    - name: redis-test
      mountPath: /src
  volumes:
    - name: redis-test # ConfigMapからボリュームを作成
      configMap: # 作成したConfigMapを指定
        name: redis-test # ConfigMap名
