apiVersion: v1
kind: Service
metadata:
  name: udp-service
spec:
  type: NodePort
  ports:
    - name: udp-port
      port: 8080
      protocol: UDP
      targetPort: 8080
  selector:
    app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: us.gcr.io/striped-proxy-187410/udp-server:latest
        ports:
        - containerPort: 8080
          protocol: UDP
